# Generated by Django 6.0.3 on 2026-03-26 17:08

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(default=movie.models.get_default_array),
        ),
    ]
